reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :subs
  resource :session 
  resources :posts, except: [:index]
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/post.rb
class Post < ApplicationRecord
    validates :title, :sub_id, :author_id, presence: true

    belongs_to :sub,
    foreign_key: :sub_id,
    class_name: :Sub

    belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

    has_many :post_subs,
        foreign_key: :post_id,
        class_name: :PostSub
        
end

reddit_clone/app/models/post_sub.rb
class PostSub < ApplicationRecord
    validates :sub_id, presence: true
    validates :post_id, presence: true
    
    belongs_to :sub,
        foreign_key: :sub_id,
        class_name: :Sub
    
    belongs_to :post,
        foreign_key: :post_id,
        class_name: :Post

    
end

reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :description, presence:true


    has_one :moderator,
        foreign_key: :sub_id,
        class_name: :User

    has_many :posts,
        foreign_key: :sub_id,
        class_name: :Post

    has_many :post_subs,
        foreign_key: :sub_id,
        class_name: :PostSub
    

end

reddit_clone/app/models/user.rb
class User < ApplicationRecord
    validates :username, :session_token, :password_digest, presence: true
    validates :username, :session_token, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}

    attr_reader :password
    before_validation :ensure_session_token

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.generate_session_token
        SecureRandom.base64
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            user
        else
            nil 
        end
    end


    belongs_to :sub,
        foreign_key: :sub_id,
        class_name: :Sub,
        optional: true

end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :require_logged_in, :logged_in?, :logout!
    #celll
    def login!(user)
        @current_user = user
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        @current_user.reset_session_token!
        session[:session_token] = nil
    end

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url if !logged_in?
    end

    def logged_in?
        !!current_user
    end
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_logged_in, except: [:show]

    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(post_params)
        
        @post.author_id = current_user.id
         
        debugger 
      

        # param titles.each  do  |title| 
            #add it to the sub_post table
                    # sp = SubPost.new(postid and subid)
                        # sp.save
        # params[:titles][i]
        p params

        titles_list = param[:titles]
        titles_list.each do |title|
            temp_sub = Sub.find_by_title(title)
            SubPost.create(sub_id: temp_sub.id, post_id: @post.id)
        end




        if @post.save
            redirect_to sub_url(@post.sub_id)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def show
        @post = Post.find(params[:id])
        render :show
    end

    def edit
        @post = Post.find(params[:id])
        if @post && current_user.id == @post.author_id
            render :edit
        end
    end

    def update
        @post = Post.find(params[:id])
        if @post && current_user.id == @post.author_id
            if @post.update(post_params)
                redirect_to sub_url(@post.sub_id)
            else
                flash.now[:errors] = @post.errors.full_messages
                render :edit
            end
        end
    end

    private
    def post_params
        params.require(:post).permit(:title, :url, :content, :sub_id, :author_id)
    end
end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, :only[:destroy]

    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = ['Invalid username or password']
            render :new
        end
    end

    def destroy 
        logout!
        redirect_to new_session_url
    end
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_logged_in, except: [:index, :show]

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(sub_params)

        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    def index
        @subs = Sub.all
        render :index
    end

    def edit
        @sub = Sub.find(params[:id])
        mod = @sub.moderator
        if @sub && @sub.id == mod.sub_id    #get checked by TA
        render :edit
        end
    end

    def update
        @sub = Sub.find(params[:id])
        mod = @sub.moderator                #get checked by TA
        if @sub && @sub.id == mod.sub_id
            if @sub.update(sub_params)
                redirect_to sub_url(@sub)
            else
                flash.now[:errors] = @sub.errors.full_messages
                render :edit
            end
        end
    end

    private
    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, only: [:destroy, :edit, :update ,:show, :index]


    def new
        @user  = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        
        # debugger

        if @user.save
            login!(@user)

            redirect_to user_url(@user)
        else
            # debugger
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end 

    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    def index
        @users = User.all
        render :index
    end

    def destroy
        @user = User.find_by(id: params[:id])
        @user.destroy if @user
        # do we need to include a logout function or one that sets the session_token to nil?

        redirect_to new_user_url
    end

    def edit
        @user = User.find(params[:id])
        render :edit
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :edit
        end
    end


    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <% if flash[:errors]%>
      <%=flash[:errors]%>
    <%end%>

    <%= yield %>
  </body>
</html>

reddit_clone/app/views/posts/new.html.erb
<h1>Create a New Post</h1>
<form action="<%=posts_url%>" method = "POST">
    <input type="hidden" name = 'authenticity_token' value = '<%= form_authenticity_token%>' >
    <ul>
        <li>
            <label>Title
                <input type="text" name = 'post[title]'>                
            </label>
        </li>
        
        <li>
            <label>url 
                <input type="text" name = 'post[url]'>                
            </label>
        </li>

        <li>
            <label>Content 
                <input type="text" name = 'post[content]'>                
            </label>
        </li>
    </ul>

    <ul>
        <% Sub.all.each do |sub| %>
            <li>
                <label><%= sub.title %>
                    <input type="checkbox" name="title[]" value="<%= sub.title %>">
                </label>
            </li>
        <% end %>
                
    </ul>
        

    <button>Create Post</button>

</form>

reddit_clone/app/views/subs/new.html.erb
<h1>Create a New Subreddit</h1>
<form action="<%=subs_url%>" method = "POST">
    <input type="hidden" name = 'authenticity_token' value = '<%= form_authenticity_token%>' >
    <ul>
        <li>
            <label>Title
                <input type="text" name = 'sub[title]'>                
            </label>
        </li>
        <li>
            <label>Description 
                <input type="text" name = 'sub[description]'>                
            </label>
        </li>
    </ul>
    <button>Create Subreddit</button>

</form>

reddit_clone/app/views/subs/show.html.erb
<h1>SHOW Subreddit!</h1>

reddit_clone/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%=users_url%>" method = "POST">
    <input type="hidden" name = 'authenticity_token' value = "<%=form_authenticity_token%>" >
    <label>Username
        <input type="text" name = 'user[username]' >
    </label>
    <label>Password
        <input type="text" name = 'user[password]' >
    </label>
    <button>Sign Up</button>

</form>

reddit_clone/app/views/users/show.html.erb
<h1>Show</h1>